In [2]:
import pandas as pd
import pandas as np
import seaborn as sns
import matplotlib.pyplot as plt

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

## Pre-process, create features, and annotate ChatGPT and Gemini paper review data
First we must label and annotate the data.
We add labels to show primary are of research and which model was used. We also flag the following features of the data:

-Figure on the first/second page [‘first_fig’]

-Number of figures, the sum of tables and figures [‘num_figures’]

-Number of references [‘num_references’]

-Number of supplementary material pages [‘num_supp_materials’]

-Research area (or keywords) [‘primary_area’] 

-The length of different sections 

-Use of mathematical equations/formulas as a proof  [‘uses_equation’] (1 - yes, 0 - no)

-Dataset sizes mentioned [‘dataset’]

In [3]:
# Read the JSON data from the file and add titles
df_gpt = pd.read_json("../json_files/chatgpt_reviews.json")
df_gemini = pd.read_json("../json_files/gemini_reviews.json")
df_gpt['model'] = 'ChatGPT'
df_gemini['model'] = 'Gemini'
df_gpt = df_gpt[["model"] + list(df_gpt.columns[:-1])]
df_gemini = df_gemini[["model"] + list(df_gemini.columns[:-1])]
titles = np.array([   
'Learning to grok: Emergence of in-context learning and skill composition in modular arithmetic tasks',
'Trading Place for Space: Increasing Location Resolution Reduces Contextual Capacity in Hippocampal Codes',
'Visual Autoregressive Modeling: Scalable Image Generation via Next-Scale Prediction',
'Cracking the Code of Juxtaposition: Can AI Models Understand the Humorous Contradictions',
'Human Expertise in Algorithmic Prediction',   
'Learning diffusion at lightspeed',  
'Weisfeiler and Leman Go Loopy: A New Hierarchy for Graph Representational Learning',    
'Unlocking the Capabilities of Thought: A Reasoning Boundary Framework to Quantify and Optimize Chain-of-Thought',
'Reinforcement Learning Under Latent Dynamics: Toward Statistical and Algorithmic Modularity',
'Generalization Error Bounds for Two-stage Recommender Systems with Tree Structure',
'Aligner: Efficient Alignment by Learning to Correct',   
'Questioning the Survey Responses of Large Language Models', 
'Stochastic Taylor Derivative Estimator: Efficient amortization for arbitrary differential operators',
'Do Finetti: On Causal Effects for Exchangeable Data',
'LLM Evaluators Recognize and Favor Their Own Generations',
'Span-Based Optimal Sample Complexity for Weakly Communicating and General Average Reward MDPs',
'Learning Formal Mathematics From Intrinsic Motivation',
'Identification and Estimation of the Bi-Directional MR with Some Invalid Instruments',   
'Maximum Entropy Inverse Reinforcement Learning of Diffusion Models with Energy-Based Models',    
'Improving Environment Novelty Quantification for Effective Unsupervised Environment Design',   
'Enhancing Preference-based Linear Bandits via Human Response Time',
'Scale Equivariant Graph Metanetworks',
'CAT3D: Create Anything in 3D with Multi-View Diffusion Models',
'Stylus: Automatic Adapter Selection for Diffusion Models',    
'The Sample-Communication Complexity Trade-off in Federated Q-Learning'
])   
    

df_columns = pd.DataFrame(titles, columns=['titles'])

# Ensure the number of rows in df_columns matches df_gpt & df_gemini
df_columns = df_columns.iloc[:len(df_gpt)].reset_index(drop=True)

# Insert "titles" as the first column in df_gpt and df_gemini
df_gpt = pd.concat([df_columns, df_gpt], axis=1)
df_gemini = pd.concat([df_columns, df_gemini], axis=1)

In [4]:
df_gpt.head()

,titles,model,Summary,Strengths and Weaknesses,Questions,Limitations,Ethical Concerns,Soundness,Presentation,Contribution,Overall Score,Confidence Score,Code of Conduct Acknowledgement
0,Learning to grok: Emergence of in-context lear...,ChatGPT,The paper investigates the emergence of in-con...,{'Originality': 'The paper explores ICL in mod...,1. Could the authors provide more details on h...,The paper acknowledges that its findings are l...,No immediate ethical concerns arise from the s...,4,3,3,7,4,I agree to abide by the NeurIPS Code of Conduct.
1,Trading Place for Space: Increasing Location R...,ChatGPT,The paper explores the contextual encoding cap...,{'Originality': 'The paper presents a novel ge...,1. How do these results compare to alternative...,The authors acknowledge the lack of direct exp...,No apparent ethical concerns.,3,3,3,7,4,I confirm that I agree to abide by the NeurIPS...
2,Visual Autoregressive Modeling: Scalable Image...,ChatGPT,The paper introduces Visual AutoRegressive mod...,{'Originality': 'The work presents a novel aut...,[Have you considered evaluating VAR on other g...,"The authors acknowledge some limitations, incl...",There are no immediate ethical concerns that w...,4,4,4,8,4,I confirm that I agree to abide by the NeurIPS...
3,Cracking the Code of Juxtaposition: Can AI Mod...,ChatGPT,The paper investigates the ability of large mu...,{'Originality': 'The work is highly original i...,[How does YESBUT compare to other humor-relate...,The authors acknowledge that AI struggles with...,There are no major ethical concerns that warra...,4,4,4,8,4,I confirm that I agree to abide by the NeurIPS...
4,Human Expertise in Algorithmic Prediction,ChatGPT,The paper introduces a novel framework for int...,{'Originality': 'The work presents an original...,[How does the framework handle scenarios where...,The authors acknowledge that their framework a...,There are no immediate ethical concerns that r...,4,4,4,8,4,I confirm that I agree to abide by the NeurIPS...

In [5]:
# -Figure on the first/second page [‘first_fig’]
# -Number of figures, the sum of tables and figures [‘num_figures’]
# -Number of references [‘num_references’]
# -Number of supplementary material pages [‘num_supp_materials’]
# -Research area (or keywords) [‘primary_area’] 
# -The length of different sections 
# -Use of mathematical equations/formulas as a proof  [‘uses_equation’] (1 - yes, 0 - no)
# -Dataset sizes mentioned [‘dataset’]

In [5]:
#Addting primary area of research column
new_col = np.array(['Interpretability and explainability', 
 'Neuroscience and cognitive science (neural coding, brain-computer interfaces)',
 'Generative models',
 'Natural language processing',
 'Human-AI interaction','Optimization (convex and non-convex, discrete, stochastic, robust)',
 'Optimization (convex and non-convex, discrete, stochastic, robust)',
 'Graph neural networks',
 'Natural language processing',
'Reinforcement learning',
'Learning theory',
'Safety in machine, learning',
'Natural language processing',
'Machine learning for physical sciences (for example: climate, physics)',
'Causal inference',
'Natural language processing',
 'Reinforcement learning',
 'Machine learning for other sciences and fields',
 'Causal inference',
'Generative models',
 'Reinforcement learning',
 'Bandits',
 'Graph neural networks',
 'Diffusion based models',
 'Reinforcement learning'])

df_columns=pd.DataFrame(new_col, columns=['primary area'])
df_gpt = pd.concat([df_gpt, df_columns], axis=1)
df_gemini = pd.concat([df_gemini, df_columns], axis=1)

# Data Annotations
Annotate data to show if there is a figure on the first page, use of equations, number of references, number of tables, number of figures, number of supplemental materials

In [6]:

first = np.array([1,1,1,1,0,1,1,0,0,0,1,1,0,1,1,0,0,1,1,1,0,0,1,1,0])
eq = np.array([1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,0,1,1])
ref= np.array([30,55,99,69,70,55,101,64,91,29,70,54,43,36,37,26,46,49,94,63,79,88,86,57,57])
tab = np.array([0,0,3,3,0,1,4,1,0,1,3,0,1,0,1,1,0,0,5,1,0,4,2,0,1])
figs = np.array([8,5,6,6,4,5,4,1,1,1,6,6,2,4,8,1,4,5,2,8,4,0,5,12,0])
supp = np.array([12,12,6,6,20,14,30,10,62,11,17,8,17,10,11,32,5,15,5,13,18,17,4,6,33])
first_df=pd.DataFrame(first, columns=['first_fig'])
eq_df=pd.DataFrame(eq, columns=['uses_equation'])
ref_df=pd.DataFrame(ref, columns=['num_references'])
tab_df=pd.DataFrame(tab, columns=['num_tables'])
figs_df=pd.DataFrame(figs, columns=['num_figures'])
supp_df=pd.DataFrame(supp, columns=['num_supp_materials'])
dfs = [first_df, eq_df, ref_df, tab_df, figs_df, supp_df]

In [7]:
for d in dfs:
    df_gpt = pd.concat([df_gpt, d], axis=1)
    df_gemini = pd.concat([df_gemini, d], axis=1)

In [8]:
df_gpt.head()

,titles,model,Summary,Strengths and Weaknesses,Questions,Limitations,Ethical Concerns,Soundness,Presentation,Contribution,Overall Score,Confidence Score,Code of Conduct Acknowledgement,primary area,first_fig,uses_equation,num_references,num_tables,num_figures,num_supp_materials
0,Learning to grok: Emergence of in-context lear...,ChatGPT,The paper investigates the emergence of in-con...,{'Originality': 'The paper explores ICL in mod...,1. Could the authors provide more details on h...,The paper acknowledges that its findings are l...,No immediate ethical concerns arise from the s...,4,3,3,7,4,I agree to abide by the NeurIPS Code of Conduct.,Interpretability and explainability,1,1,30,0,8,12
1,Trading Place for Space: Increasing Location R...,ChatGPT,The paper explores the contextual encoding cap...,{'Originality': 'The paper presents a novel ge...,1. How do these results compare to alternative...,The authors acknowledge the lack of direct exp...,No apparent ethical concerns.,3,3,3,7,4,I confirm that I agree to abide by the NeurIPS...,Neuroscience and cognitive science (neural cod...,1,1,55,0,5,12
2,Visual Autoregressive Modeling: Scalable Image...,ChatGPT,The paper introduces Visual AutoRegressive mod...,{'Originality': 'The work presents a novel aut...,[Have you considered evaluating VAR on other g...,"The authors acknowledge some limitations, incl...",There are no immediate ethical concerns that w...,4,4,4,8,4,I confirm that I agree to abide by the NeurIPS...,Generative models,1,1,99,3,6,6
3,Cracking the Code of Juxtaposition: Can AI Mod...,ChatGPT,The paper investigates the ability of large mu...,{'Originality': 'The work is highly original i...,[How does YESBUT compare to other humor-relate...,The authors acknowledge that AI struggles with...,There are no major ethical concerns that warra...,4,4,4,8,4,I confirm that I agree to abide by the NeurIPS...,Natural language processing,1,0,69,3,6,6
4,Human Expertise in Algorithmic Prediction,ChatGPT,The paper introduces a novel framework for int...,{'Originality': 'The work presents an original...,[How does the framework handle scenarios where...,The authors acknowledge that their framework a...,There are no immediate ethical concerns that r...,4,4,4,8,4,I confirm that I agree to abide by the NeurIPS...,Human-AI interaction,0,1,70,0,4,20

In [11]:
df_gemini.to_excel("../LLM output data/gemini_sheet.xlsx", sheet_name="Sheet1", index=True)
df_gpt.to_excel("../LLM output data/gpt_sheet.xlsx", sheet_name="Sheet1", index=True)
print("Excel file saved successfully!")

Excel file saved successfully!

# Compile all the data 
This step is done on excel. Once all data is compiled, we can begin our analysis.

Now we import all files to merge and create one dataframe.

In [10]:
#processing the data
file_path = "../LLM output data/LLM Review Output.xlsx"

df_sheet1 = pd.read_excel(file_path, sheet_name="Output-NG")
df_sheet2 = pd.read_excel(file_path, sheet_name="Output-Ying")
df_sheet3 = pd.read_excel(file_path, sheet_name="Outout-JM")
df_sheet4 = pd.read_excel(file_path, sheet_name="reject_41_83_JM")

df_sheet1['Paper_index'] = df_sheet1['Paper_index'].astype(int)
df_sheet2['Paper_index'] = df_sheet2['Paper_index'].astype(int)
df_sheet3['Paper_index'] = df_sheet3['Paper_index'].astype(int)
df_sheet1=df_sheet1.set_index('Paper_index')
df_sheet2=df_sheet2.set_index('Paper_index')
df_sheet3=df_sheet3.set_index('Paper_index')

df= pd.concat([df_sheet1, df_sheet2, df_sheet3])

print(df_sheet1.shape)
print(df_sheet2.shape)
print(df_sheet3.shape)
print(df.shape)

(50, 20)
(50, 22)
(22, 22)
(122, 22)

In [14]:
df= pd.concat([df_sheet1, df_sheet2, df_sheet3])
df= pd.concat([df_sheet1, df_sheet2, df_sheet3])

In [15]:

#checking occurences to make sure all titles appear twice since we are comparing two models
title_counts = df['Title'].value_counts()

#identify if title appears more 1-5 times
num=[1,2,3,4]
for n in num:
    num_count= (df[df['Title'].isin(title_counts[title_counts == n].index)]).shape[0]
    print('number of titles that appear ' + str(n) + " times is " + str(num_count))

number of titles that appear 1 times is 0
number of titles that appear 2 times is 122
number of titles that appear 3 times is 0
number of titles that appear 4 times is 0